version: '3.8'

services:
  bookkeeper-service:
    image: bookkeeper:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  book-service:
    image: bookservice:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  bookreader-service:
    image: bookreader:latest
    ports:
      - "8082:8082"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge